-- Your SQL goes here
CREATE TABLE BLOGS(
    ID SERIAL PRIMARY KEY NOT NULL,
    TITLE VARCHAR NOT NULL,
    BODY VARCHAR NOT NULL,
    CREATOR_ID INTEGER NOT NULL,
    CREATED_TIME BIGINT NOT NULL,
    LAST_EDITED_TIME BIGINT NOT NULL,
    LIKES INT NOT NULL
);